### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by thetechnick** [kubermatic/kubecarrier#16]
**Is your feature request related to a problem? Please describe.**
We're missing documentation. We need documentation for kubecarrier. 

**Describe the solution you'd like**
The resulting kubecarrier documentation should have the following elements:

* [x] Quick start guide
* [x] Concepts --> 10000-foot kubecarrier overview and basic concepts the user should know about
* [x] Tutorials 
* [x] Tasks
    * [x] Adding new provider, service cluster, tenant, etc.
* [x] API Reference --> this shall be autogenerated

**Additional context**

Here are some decent links I've gathered this information and they explain in more depth:

* https://www.sohamkamani.com/blog/how-to-write-good-documentation/
* https://kubernetes.io/docs/home/
