### ISSUE TITLE
[Feature]  e2e operator 

### ISSUE THREAD

**Issue by nmiculinic** [kubermatic/kubecarrier#296]
**Is your feature request related to a problem? Please describe.**

Since we're at KubeCarrier feature complete stage, we require a simple e2e  test operator for our e2e test suites. This issue is a root epic issue over various features the e2e operator should contain, as well as providing additional context/discussion for this matter. 

Currently required features: 

* [ ] basic test operator with a simple schema divided into spec and status. The operator should make the semantic sense, and have rounded up story and mental model. It should be a simplified version of existing operator CRD, simple enough for the test use case, but "feature complete"  to represent realistic workload the kubecarrier shall manage. 
* [ ] define some fields as required in the spec.
* [ ] Implement related operator CRD, which is extra CRD object which is created on behalf of other CRD. The simplest example would be backup/snapshot/restore CRDs. When database backup CRD is created, the e2e-test operator should create a Snapshot CRD object. This allows us to test the catapult's adoption controller. 
* [ ] Implement defaulting/mutating webhook for the operator
* [ ] multiple CRD versions and conversion webhook between different CRD version for the operator
